list: $/pensoft/getinvolved/models/interest/columns.yaml
modelClass: Pensoft\GetInvolved\Models\Interest
title: Interests
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/getinvolved/interests/update/:id'
